copy ../smexample/*smexample* to ./, then "pcc  -u smexample -f useit.php"


tim@beer:~/phpoo/tidbits/libinclude-test/useit$ pcc  -u smexample -f useit.php
go for broke
yay!  you've included common.inc
path stripping appears to be working.
woo!


tim@beer:~/phpoo/tidbits/libinclude-test/useit$ pcc  -u smexample  useit.php
tim@beer:~/phpoo/tidbits/libinclude-test/useit$ ./useit
go for broke
yay!  you've included common.inc
path stripping appears to be working.
woo!

