interpret the script by cd'ing to home/ and saying

pcc -I `pwd`/../redist/pear -f index.php

compile the library by saying:

pcc -rm -d 5 -l smexample home/index.php admin/common.inc redist/pear/apear.php --strip-path redist/pear 

don't forget to add --force-rebuild if you changed code generation

