(module glade-binding
   (import (gtk-binding "cigloo/gtk.scm"))
   (extern
    (include "glade/glade.h")

;;    cat /usr/include/libglade-2.0/glade/glade-init.h  |grep -v DECLS |cigloo -int-enum -macro -type GtkFrame -type GtkWidget -type GtkAccelGroup -type GtkFrameClass -type guint  -type gchar -type GObject -type GObjectClass -type gboolean -type GType -type GCallback -type gpointer -type GList -type gint
    (macro glade_init::void () "glade_init")
    (macro glade_require::void (gchar*) "glade_require")
    (macro glade_provide::void (gchar*) "glade_provide")
;    (type void->void "void ($(void))")
;    (type gchar* (pointer gchar) "gchar *")
 ;   (type gchar*->void "void ($(gchar *))")
    
;;    cat /usr/include/libglade-2.0/glade/glade-xml.h  |grep -v DECLS  |cigloo -int-enum -macro -type GtkFrame -type GtkWidget -type GtkAccelGroup -type GtkFrameClass -type guint  -type gchar -type GObject -type GObjectClass -type gboolean -type GType -type GCallback -type gpointer -type GList -type gint 
   (macro GLADE_TYPE_XML::int "GLADE_TYPE_XML")
   (macro GLADE_XML::s-_GladeXML* (obj::cobj) "GLADE_XML")
   ;(macro GLADE_XML_CLASS::int (int) "GLADE_XML_CLASS")
   (macro GLADE_IS_XML::int (int) "GLADE_IS_XML")
   (macro GLADE_IS_XML_CLASS::int (int) "GLADE_IS_XML_CLASS")
   (macro GLADE_XML_GET_CLASS::int (int) "GLADE_XML_GET_CLASS")
   (macro glade_xml_get_type::GType () "glade_xml_get_type")
   (macro glade_xml_new::GladeXML* (string string string) "glade_xml_new")
   (macro glade_xml_new_from_buffer::GladeXML* (string int string string) "glade_xml_new_from_buffer")
   (macro glade_xml_construct::gboolean (GladeXML* string string string) "glade_xml_construct")
   (macro glade_xml_signal_connect::void (GladeXML* string GCallback) "glade_xml_signal_connect")
   (macro glade_xml_signal_connect_data::void (GladeXML* string GCallback gpointer) "glade_xml_signal_connect_data")
   (macro glade_xml_signal_autoconnect::void (GladeXML*) "glade_xml_signal_autoconnect")
   (macro glade_xml_signal_connect_full::void (GladeXML* gchar* GladeXMLConnectFunc gpointer) "glade_xml_signal_connect_full")
   (macro glade_xml_signal_autoconnect_full::void (GladeXML* GladeXMLConnectFunc gpointer) "glade_xml_signal_autoconnect_full")
   (macro glade_xml_get_widget::GtkWidget* (GladeXML* string) "glade_xml_get_widget")
   (macro glade_xml_get_widget_prefix::GList* (GladeXML* string) "glade_xml_get_widget_prefix")
   (macro glade_xml_relative_file::gchar* (GladeXML* gchar*) "glade_xml_relative_file")
   (macro glade_get_widget_name::string (GtkWidget*) "glade_get_widget_name")
   (macro glade_get_widget_tree::GladeXML* (GtkWidget*) "glade_get_widget_tree")
   (macro glade_set_custom_handler::void (GladeXMLCustomWidgetHandler gpointer) "glade_set_custom_handler")

   ;; this block of types is duplicated from gtk.scm... hrnf.
   (type gchar char "gchar")
   (type s-_GObject (struct (g_type_instance::GTypeInstance "g_type_instance") (ref_count::guint "ref_count") (qdata::GData* "qdata")) "struct _GObject")
   (type GObject s-_GObject "GObject")
       (type s-_GtkWidget (struct (object::GtkObject "object") (private_flags::guint16 "private_flags") (state::guint8 "state") (saved_state::guint8 "saved_state") (name::gchar* "name") (style::GtkStyle* "style") (requisition::GtkRequisition "requisition") (allocation::GtkAllocation "allocation") (window::GdkWindow* "window") (parent::GtkWidget* "parent")) "struct _GtkWidget")
    (type GtkWidget s-_GtkWidget "GtkWidget")
    (type s-_GList (struct (data::gpointer "data") (next::GList* "next") (prev::GList* "prev")) "struct _GList")
    (type GList s-_GList "GList")

   
   (type s-_GladeXML (struct (parent::GObject "parent") (filename::string "filename") (priv::GladeXMLPrivate* "priv")) "struct _GladeXML")
   (type GladeXML s-_GladeXML "GladeXML")
   (type s-_GladeXMLClass (struct (parent_class::GObjectClass "parent_class") (lookup_type::*GladeXML*,string->GType "lookup_type")) "struct _GladeXMLClass")
   (type GladeXMLClass s-_GladeXMLClass "GladeXMLClass")
   (type s-_GladeXMLPrivate (struct) "struct _GladeXMLPrivate")
   (type GladeXMLPrivate s-_GladeXMLPrivate "GladeXMLPrivate")
   (type GladeXML*,string->GType "GType ($(GladeXML *,char *))")
   (type *GladeXML*,string->GType (function GType (GladeXML* string)) "GType ((*$)(GladeXML *,char *))")
   (type gchar* (pointer gchar) "gchar *")
   (type GObject* (pointer GObject) "GObject *")
   (type gchar*,GObject*,gchar*,gchar*,GObject*,gboolean,gpointer->void "void ($(gchar *,GObject *,gchar *,gchar *,GObject *,gboolean,gpointer))")
   (type *gchar*,GObject*,gchar*,gchar*,GObject*,gboolean,gpointer->void (function void (gchar* GObject* gchar* gchar* GObject* gboolean gpointer)) "void ((*$)(gchar *,GObject *,gchar *,gchar *,GObject *,gboolean,gpointer))")
   (type GladeXMLConnectFunc *gchar*,GObject*,gchar*,gchar*,GObject*,gboolean,gpointer->void "GladeXMLConnectFunc")
   (type GtkWidget* (pointer GtkWidget) "GtkWidget *")
   (type GladeXML*,gchar*,gchar*,gchar*,gchar*,gint,gint,gpointer->GtkWidget* "GtkWidget *($(GladeXML *,gchar *,gchar *,gchar *,gchar *,gint,gint,gpointer))")
   (type *GladeXML*,gchar*,gchar*,gchar*,gchar*,gint,gint,gpointer->GtkWidget* (function GtkWidget* (GladeXML* gchar* gchar* gchar* gchar* gint gint gpointer)) "GtkWidget *((*$)(GladeXML *,gchar *,gchar *,gchar *,gchar *,gint,gint,gpointer))")
   (type GladeXMLCustomWidgetHandler *GladeXML*,gchar*,gchar*,gchar*,gchar*,gint,gint,gpointer->GtkWidget* "GladeXMLCustomWidgetHandler")
;   (type void->GType "GType ($(void))")
   (type string,string,string->GladeXML* "GladeXML *($(char *,char *,char *))")
   (type string,int,string,string->GladeXML* "GladeXML *($(char *,int,char *,char *))")
   (type GladeXML*,string,string,string->gboolean "gboolean ($(GladeXML *,char *,char *,char *))")
   (type GladeXML*,string,GCallback->void "void ($(GladeXML *,char *,GCallback))")
   (type GladeXML*,string,GCallback,gpointer->void "void ($(GladeXML *,char *,GCallback,gpointer))")
   (type GladeXML*->void "void ($(GladeXML *))")
   (type GladeXML*,gchar*,GladeXMLConnectFunc,gpointer->void "void ($(GladeXML *,gchar *,GladeXMLConnectFunc,gpointer))")
   (type GladeXML*,GladeXMLConnectFunc,gpointer->void "void ($(GladeXML *,GladeXMLConnectFunc,gpointer))")
   (type GladeXML*,string->GtkWidget* "GtkWidget *($(GladeXML *,char *))")
   (type GList* (pointer GList) "GList *")
   (type GladeXML*,string->GList* "GList *($(GladeXML *,char *))")
   (type GladeXML*,gchar*->gchar* "gchar *($(GladeXML *,gchar *))")
   (type GtkWidget*->string "char *($(GtkWidget *))")
   (type GtkWidget*->GladeXML* "GladeXML *($(GtkWidget *))")
   (type GladeXMLCustomWidgetHandler,gpointer->void "void ($(GladeXMLCustomWidgetHandler,gpointer))")   ))


;; I think this has to get called before gtk_init, or weird shit
;; happens (the gtk type system gets shat on).
(begin (glade_init) 0)
