;; generated using
;; cigloo -macro -type GtkFrame -type GtkWidget -type GtkAccelGroup -type GtkFrameClass -type guint /usr/include/gtkscintilla.h > gtkscintilla.scm
(module gtkscintilla-binding
   (import (gtk-binding "cigloo/gtk.scm"))
   (extern
    (include "gtk/gtk.h")
    (include "gtkscintilla.h")
    ;; beginning of /usr/include/gtkscintilla.h
    (macro GTK_TYPE_SCINTILLA::int "GTK_TYPE_SCINTILLA")
;    (macro GTK_SCINTILLA::GtkScintilla* (void*) "GTK_SCINTILLA")
    (macro GTK_SCINTILLA::GtkScintilla* (cobj) "GTK_SCINTILLA")
    (macro GTK_SCINTILLA_CLASS::int (int) "GTK_SCINTILLA_CLASS")
    (macro GTK_IS_SCINTILLA::int (int) "GTK_IS_SCINTILLA")
    (macro GTK_IS_SCINTILLA_CLASS::int (int) "GTK_IS_SCINTILLA_CLASS")
    (macro INVALID_POSITION::int "INVALID_POSITION")
    (macro SCI_START::long "SCI_START")
    (macro SCI_OPTIONAL_START::long "SCI_OPTIONAL_START")
    (macro SCI_LEXER_START::long "SCI_LEXER_START")
    (macro SCWS_INVISIBLE::long "SCWS_INVISIBLE")
    (macro SCWS_VISIBLEALWAYS::long "SCWS_VISIBLEALWAYS")
    (macro SCWS_VISIBLEAFTERINDENT::long "SCWS_VISIBLEAFTERINDENT")
    (macro SC_EOL_CRLF::long "SC_EOL_CRLF")
    (macro SC_EOL_CR::long "SC_EOL_CR")
    (macro SC_EOL_LF::long "SC_EOL_LF")
    (macro SC_CP_UTF8::long "SC_CP_UTF8")
    (macro MARKER_MAX::long "MARKER_MAX")
    (macro SC_MARK_CIRCLE::long "SC_MARK_CIRCLE")
    (macro SC_MARK_ROUNDRECT::long "SC_MARK_ROUNDRECT")
    (macro SC_MARK_ARROW::long "SC_MARK_ARROW")
    (macro SC_MARK_SMALLRECT::long "SC_MARK_SMALLRECT")
    (macro SC_MARK_SHORTARROW::long "SC_MARK_SHORTARROW")
    (macro SC_MARK_EMPTY::long "SC_MARK_EMPTY")
    (macro SC_MARK_ARROWDOWN::long "SC_MARK_ARROWDOWN")
    (macro SC_MARK_MINUS::long "SC_MARK_MINUS")
    (macro SC_MARK_PLUS::long "SC_MARK_PLUS")
    (macro SC_MARK_VLINE::long "SC_MARK_VLINE")
    (macro SC_MARK_LCORNER::long "SC_MARK_LCORNER")
    (macro SC_MARK_TCORNER::long "SC_MARK_TCORNER")
    (macro SC_MARK_BOXPLUS::long "SC_MARK_BOXPLUS")
    (macro SC_MARK_BOXPLUSCONNECTED::long "SC_MARK_BOXPLUSCONNECTED")
    (macro SC_MARK_BOXMINUS::long "SC_MARK_BOXMINUS")
    (macro SC_MARK_BOXMINUSCONNECTED::long "SC_MARK_BOXMINUSCONNECTED")
    (macro SC_MARK_LCORNERCURVE::long "SC_MARK_LCORNERCURVE")
    (macro SC_MARK_TCORNERCURVE::long "SC_MARK_TCORNERCURVE")
    (macro SC_MARK_CIRCLEPLUS::long "SC_MARK_CIRCLEPLUS")
    (macro SC_MARK_CIRCLEPLUSCONNECTED::long "SC_MARK_CIRCLEPLUSCONNECTED")
    (macro SC_MARK_CIRCLEMINUS::long "SC_MARK_CIRCLEMINUS")
    (macro SC_MARK_CIRCLEMINUSCONNECTED::long "SC_MARK_CIRCLEMINUSCONNECTED")
    (macro SC_MARK_BACKGROUND::long "SC_MARK_BACKGROUND")
    (macro SC_MARK_CHARACTER::long "SC_MARK_CHARACTER")
    (macro SC_MARKNUM_FOLDEREND::long "SC_MARKNUM_FOLDEREND")
    (macro SC_MARKNUM_FOLDEROPENMID::long "SC_MARKNUM_FOLDEROPENMID")
    (macro SC_MARKNUM_FOLDERMIDTAIL::long "SC_MARKNUM_FOLDERMIDTAIL")
    (macro SC_MARKNUM_FOLDERTAIL::long "SC_MARKNUM_FOLDERTAIL")
    (macro SC_MARKNUM_FOLDERSUB::long "SC_MARKNUM_FOLDERSUB")
    (macro SC_MARKNUM_FOLDER::long "SC_MARKNUM_FOLDER")
    (macro SC_MARKNUM_FOLDEROPEN::long "SC_MARKNUM_FOLDEROPEN")
    (macro SC_MASK_FOLDERS::long "SC_MASK_FOLDERS")
    (macro SC_MARGIN_SYMBOL::long "SC_MARGIN_SYMBOL")
    (macro SC_MARGIN_NUMBER::long "SC_MARGIN_NUMBER")
    (macro STYLE_DEFAULT::long "STYLE_DEFAULT")
    (macro STYLE_LINENUMBER::long "STYLE_LINENUMBER")
    (macro STYLE_BRACELIGHT::long "STYLE_BRACELIGHT")
    (macro STYLE_BRACEBAD::long "STYLE_BRACEBAD")
    (macro STYLE_CONTROLCHAR::long "STYLE_CONTROLCHAR")
    (macro STYLE_INDENTGUIDE::long "STYLE_INDENTGUIDE")
    (macro STYLE_LASTPREDEFINED::long "STYLE_LASTPREDEFINED")
    (macro STYLE_MAX::long "STYLE_MAX")
    (macro SC_CHARSET_ANSI::long "SC_CHARSET_ANSI")
    (macro SC_CHARSET_DEFAULT::long "SC_CHARSET_DEFAULT")
    (macro SC_CHARSET_BALTIC::long "SC_CHARSET_BALTIC")
    (macro SC_CHARSET_CHINESEBIG5::long "SC_CHARSET_CHINESEBIG5")
    (macro SC_CHARSET_EASTEUROPE::long "SC_CHARSET_EASTEUROPE")
    (macro SC_CHARSET_GB2312::long "SC_CHARSET_GB2312")
    (macro SC_CHARSET_GREEK::long "SC_CHARSET_GREEK")
    (macro SC_CHARSET_HANGUL::long "SC_CHARSET_HANGUL")
    (macro SC_CHARSET_MAC::long "SC_CHARSET_MAC")
    (macro SC_CHARSET_OEM::long "SC_CHARSET_OEM")
    (macro SC_CHARSET_RUSSIAN::long "SC_CHARSET_RUSSIAN")
    (macro SC_CHARSET_SHIFTJIS::long "SC_CHARSET_SHIFTJIS")
    (macro SC_CHARSET_SYMBOL::long "SC_CHARSET_SYMBOL")
    (macro SC_CHARSET_TURKISH::long "SC_CHARSET_TURKISH")
    (macro SC_CHARSET_JOHAB::long "SC_CHARSET_JOHAB")
    (macro SC_CHARSET_HEBREW::long "SC_CHARSET_HEBREW")
    (macro SC_CHARSET_ARABIC::long "SC_CHARSET_ARABIC")
    (macro SC_CHARSET_VIETNAMESE::long "SC_CHARSET_VIETNAMESE")
    (macro SC_CHARSET_THAI::long "SC_CHARSET_THAI")
    (macro SC_CASE_MIXED::long "SC_CASE_MIXED")
    (macro SC_CASE_UPPER::long "SC_CASE_UPPER")
    (macro SC_CASE_LOWER::long "SC_CASE_LOWER")
    (macro INDIC_MAX::long "INDIC_MAX")
    (macro INDIC_PLAIN::long "INDIC_PLAIN")
    (macro INDIC_SQUIGGLE::long "INDIC_SQUIGGLE")
    (macro INDIC_TT::long "INDIC_TT")
    (macro INDIC_DIAGONAL::long "INDIC_DIAGONAL")
    (macro INDIC_STRIKE::long "INDIC_STRIKE")
    (macro INDIC0_MASK::long "INDIC0_MASK")
    (macro INDIC1_MASK::long "INDIC1_MASK")
    (macro INDIC2_MASK::long "INDIC2_MASK")
    (macro INDICS_MASK::long "INDICS_MASK")
    (macro SC_PRINT_NORMAL::long "SC_PRINT_NORMAL")
    (macro SC_PRINT_INVERTLIGHT::long "SC_PRINT_INVERTLIGHT")
    (macro SC_PRINT_BLACKONWHITE::long "SC_PRINT_BLACKONWHITE")
    (macro SC_PRINT_COLOURONWHITE::long "SC_PRINT_COLOURONWHITE")
    (macro SC_PRINT_COLOURONWHITEDEFAULTBG::long "SC_PRINT_COLOURONWHITEDEFAULTBG")
    (macro SCFIND_WHOLEWORD::long "SCFIND_WHOLEWORD")
    (macro SCFIND_MATCHCASE::long "SCFIND_MATCHCASE")
    (macro SCFIND_WORDSTART::long "SCFIND_WORDSTART")
    (macro SCFIND_REGEXP::long "SCFIND_REGEXP")
    (macro SC_FOLDLEVELBASE::long "SC_FOLDLEVELBASE")
    (macro SC_FOLDLEVELWHITEFLAG::long "SC_FOLDLEVELWHITEFLAG")
    (macro SC_FOLDLEVELHEADERFLAG::long "SC_FOLDLEVELHEADERFLAG")
    (macro SC_FOLDLEVELNUMBERMASK::long "SC_FOLDLEVELNUMBERMASK")
    (macro SC_TIME_FOREVER::long "SC_TIME_FOREVER")
    (macro SC_WRAP_NONE::long "SC_WRAP_NONE")
    (macro SC_WRAP_WORD::long "SC_WRAP_WORD")
    (macro EDGE_NONE::long "EDGE_NONE")
    (macro EDGE_LINE::long "EDGE_LINE")
    (macro EDGE_BACKGROUND::long "EDGE_BACKGROUND")
    (macro CARET_SLOP::long "CARET_SLOP")
    (macro CARET_CENTER::long "CARET_CENTER")
    (macro CARET_STRICT::long "CARET_STRICT")
    (macro CARET_XEVEN::long "CARET_XEVEN")
    (macro CARET_XJUMPS::long "CARET_XJUMPS")
    (macro SC_CURSORNORMAL::int "SC_CURSORNORMAL")
    (macro SC_CURSORWAIT::long "SC_CURSORWAIT")
    (macro VISIBLE_SLOP::long "VISIBLE_SLOP")
    (macro VISIBLE_STRICT::long "VISIBLE_STRICT")
    (macro SC_MOD_INSERTTEXT::long "SC_MOD_INSERTTEXT")
    (macro SC_MOD_DELETETEXT::long "SC_MOD_DELETETEXT")
    (macro SC_MOD_CHANGESTYLE::long "SC_MOD_CHANGESTYLE")
    (macro SC_MOD_CHANGEFOLD::long "SC_MOD_CHANGEFOLD")
    (macro SC_PERFORMED_USER::long "SC_PERFORMED_USER")
    (macro SC_PERFORMED_UNDO::long "SC_PERFORMED_UNDO")
    (macro SC_PERFORMED_REDO::long "SC_PERFORMED_REDO")
    (macro SC_LASTSTEPINUNDOREDO::long "SC_LASTSTEPINUNDOREDO")
    (macro SC_MOD_CHANGEMARKER::long "SC_MOD_CHANGEMARKER")
    (macro SC_MOD_BEFOREINSERT::long "SC_MOD_BEFOREINSERT")
    (macro SC_MOD_BEFOREDELETE::long "SC_MOD_BEFOREDELETE")
    (macro SC_MODEVENTMASKALL::long "SC_MODEVENTMASKALL")
    (macro SCEN_CHANGE::long "SCEN_CHANGE")
    (macro SCEN_SETFOCUS::long "SCEN_SETFOCUS")
    (macro SCEN_KILLFOCUS::long "SCEN_KILLFOCUS")
    (macro SCK_DOWN::long "SCK_DOWN")
    (macro SCK_UP::long "SCK_UP")
    (macro SCK_LEFT::long "SCK_LEFT")
    (macro SCK_RIGHT::long "SCK_RIGHT")
    (macro SCK_HOME::long "SCK_HOME")
    (macro SCK_END::long "SCK_END")
    (macro SCK_PRIOR::long "SCK_PRIOR")
    (macro SCK_NEXT::long "SCK_NEXT")
    (macro SCK_DELETE::long "SCK_DELETE")
    (macro SCK_INSERT::long "SCK_INSERT")
    (macro SCK_ESCAPE::long "SCK_ESCAPE")
    (macro SCK_BACK::long "SCK_BACK")
    (macro SCK_TAB::long "SCK_TAB")
    (macro SCK_RETURN::long "SCK_RETURN")
    (macro SCK_ADD::long "SCK_ADD")
    (macro SCK_SUBTRACT::long "SCK_SUBTRACT")
    (macro SCK_DIVIDE::long "SCK_DIVIDE")
    (macro SCMOD_SHIFT::long "SCMOD_SHIFT")
    (macro SCMOD_CTRL::long "SCMOD_CTRL")
    (macro SCMOD_ALT::long "SCMOD_ALT")
    (macro SCLEX_CONTAINER::long "SCLEX_CONTAINER")
    (macro SCLEX_NULL::long "SCLEX_NULL")
    (macro SCLEX_PYTHON::long "SCLEX_PYTHON")
    (macro SCLEX_CPP::long "SCLEX_CPP")
    (macro SCLEX_HTML::long "SCLEX_HTML")
    (macro SCLEX_XML::long "SCLEX_XML")
    (macro SCLEX_PERL::long "SCLEX_PERL")
    (macro SCLEX_SQL::long "SCLEX_SQL")
    (macro SCLEX_VB::long "SCLEX_VB")
    (macro SCLEX_PROPERTIES::long "SCLEX_PROPERTIES")
    (macro SCLEX_ERRORLIST::long "SCLEX_ERRORLIST")
    (macro SCLEX_MAKEFILE::long "SCLEX_MAKEFILE")
    (macro SCLEX_BATCH::long "SCLEX_BATCH")
    (macro SCLEX_XCODE::long "SCLEX_XCODE")
    (macro SCLEX_LATEX::long "SCLEX_LATEX")
    (macro SCLEX_LUA::long "SCLEX_LUA")
    (macro SCLEX_DIFF::long "SCLEX_DIFF")
    (macro SCLEX_CONF::long "SCLEX_CONF")
    (macro SCLEX_PASCAL::long "SCLEX_PASCAL")
    (macro SCLEX_AVE::long "SCLEX_AVE")
    (macro SCLEX_ADA::long "SCLEX_ADA")
    (macro SCLEX_LISP::long "SCLEX_LISP")
    (macro SCLEX_RUBY::long "SCLEX_RUBY")
    (macro SCLEX_EIFFEL::long "SCLEX_EIFFEL")
    (macro SCLEX_EIFFELKW::long "SCLEX_EIFFELKW")
    (macro SCLEX_TCL::long "SCLEX_TCL")
    (macro SCLEX_NNCRONTAB::long "SCLEX_NNCRONTAB")
    (macro SCLEX_BULLANT::long "SCLEX_BULLANT")
    (macro SCLEX_VBSCRIPT::long "SCLEX_VBSCRIPT")
    (macro SCLEX_ASP::long "SCLEX_ASP")
    (macro SCLEX_PHP::long "SCLEX_PHP")
    (macro SCLEX_BAAN::long "SCLEX_BAAN")
    (macro SCLEX_AUTOMATIC::long "SCLEX_AUTOMATIC")
    (macro SCE_P_DEFAULT::long "SCE_P_DEFAULT")
    (macro SCE_P_COMMENTLINE::long "SCE_P_COMMENTLINE")
    (macro SCE_P_NUMBER::long "SCE_P_NUMBER")
    (macro SCE_P_STRING::long "SCE_P_STRING")
    (macro SCE_P_CHARACTER::long "SCE_P_CHARACTER")
    (macro SCE_P_WORD::long "SCE_P_WORD")
    (macro SCE_P_TRIPLE::long "SCE_P_TRIPLE")
    (macro SCE_P_TRIPLEDOUBLE::long "SCE_P_TRIPLEDOUBLE")
    (macro SCE_P_CLASSNAME::long "SCE_P_CLASSNAME")
    (macro SCE_P_DEFNAME::long "SCE_P_DEFNAME")
    (macro SCE_P_OPERATOR::long "SCE_P_OPERATOR")
    (macro SCE_P_IDENTIFIER::long "SCE_P_IDENTIFIER")
    (macro SCE_P_COMMENTBLOCK::long "SCE_P_COMMENTBLOCK")
    (macro SCE_P_STRINGEOL::long "SCE_P_STRINGEOL")
    (macro SCE_C_DEFAULT::long "SCE_C_DEFAULT")
    (macro SCE_C_COMMENT::long "SCE_C_COMMENT")
    (macro SCE_C_COMMENTLINE::long "SCE_C_COMMENTLINE")
    (macro SCE_C_COMMENTDOC::long "SCE_C_COMMENTDOC")
    (macro SCE_C_NUMBER::long "SCE_C_NUMBER")
    (macro SCE_C_WORD::long "SCE_C_WORD")
    (macro SCE_C_STRING::long "SCE_C_STRING")
    (macro SCE_C_CHARACTER::long "SCE_C_CHARACTER")
    (macro SCE_C_UUID::long "SCE_C_UUID")
    (macro SCE_C_PREPROCESSOR::long "SCE_C_PREPROCESSOR")
    (macro SCE_C_OPERATOR::long "SCE_C_OPERATOR")
    (macro SCE_C_IDENTIFIER::long "SCE_C_IDENTIFIER")
    (macro SCE_C_STRINGEOL::long "SCE_C_STRINGEOL")
    (macro SCE_C_VERBATIM::long "SCE_C_VERBATIM")
    (macro SCE_C_REGEX::long "SCE_C_REGEX")
    (macro SCE_C_COMMENTLINEDOC::long "SCE_C_COMMENTLINEDOC")
    (macro SCE_C_WORD2::long "SCE_C_WORD2")
    (macro SCE_C_COMMENTDOCKEYWORD::long "SCE_C_COMMENTDOCKEYWORD")
    (macro SCE_C_COMMENTDOCKEYWORDERROR::long "SCE_C_COMMENTDOCKEYWORDERROR")
    (macro SCE_B_DEFAULT::long "SCE_B_DEFAULT")
    (macro SCE_B_COMMENT::long "SCE_B_COMMENT")
    (macro SCE_B_NUMBER::long "SCE_B_NUMBER")
    (macro SCE_B_KEYWORD::long "SCE_B_KEYWORD")
    (macro SCE_B_STRING::long "SCE_B_STRING")
    (macro SCE_B_PREPROCESSOR::long "SCE_B_PREPROCESSOR")
    (macro SCE_B_OPERATOR::long "SCE_B_OPERATOR")
    (macro SCE_B_IDENTIFIER::long "SCE_B_IDENTIFIER")
    (macro SCE_B_DATE::long "SCE_B_DATE")
    (macro SCE_H_DEFAULT::long "SCE_H_DEFAULT")
    (macro SCE_H_TAG::long "SCE_H_TAG")
    (macro SCE_H_TAGUNKNOWN::long "SCE_H_TAGUNKNOWN")
    (macro SCE_H_ATTRIBUTE::long "SCE_H_ATTRIBUTE")
    (macro SCE_H_ATTRIBUTEUNKNOWN::long "SCE_H_ATTRIBUTEUNKNOWN")
    (macro SCE_H_NUMBER::long "SCE_H_NUMBER")
    (macro SCE_H_DOUBLESTRING::long "SCE_H_DOUBLESTRING")
    (macro SCE_H_SINGLESTRING::long "SCE_H_SINGLESTRING")
    (macro SCE_H_OTHER::long "SCE_H_OTHER")
    (macro SCE_H_COMMENT::long "SCE_H_COMMENT")
    (macro SCE_H_ENTITY::long "SCE_H_ENTITY")
    (macro SCE_H_TAGEND::long "SCE_H_TAGEND")
    (macro SCE_H_XMLSTART::long "SCE_H_XMLSTART")
    (macro SCE_H_XMLEND::long "SCE_H_XMLEND")
    (macro SCE_H_SCRIPT::long "SCE_H_SCRIPT")
    (macro SCE_H_ASP::long "SCE_H_ASP")
    (macro SCE_H_ASPAT::long "SCE_H_ASPAT")
    (macro SCE_H_CDATA::long "SCE_H_CDATA")
    (macro SCE_H_QUESTION::long "SCE_H_QUESTION")
    (macro SCE_H_VALUE::long "SCE_H_VALUE")
    (macro SCE_H_XCCOMMENT::long "SCE_H_XCCOMMENT")
    (macro SCE_H_SGML_DEFAULT::long "SCE_H_SGML_DEFAULT")
    (macro SCE_H_SGML_COMMAND::long "SCE_H_SGML_COMMAND")
    (macro SCE_H_SGML_1ST_PARAM::long "SCE_H_SGML_1ST_PARAM")
    (macro SCE_H_SGML_DOUBLESTRING::long "SCE_H_SGML_DOUBLESTRING")
    (macro SCE_H_SGML_SIMPLESTRING::long "SCE_H_SGML_SIMPLESTRING")
    (macro SCE_H_SGML_ERROR::long "SCE_H_SGML_ERROR")
    (macro SCE_H_SGML_SPECIAL::long "SCE_H_SGML_SPECIAL")
    (macro SCE_H_SGML_ENTITY::long "SCE_H_SGML_ENTITY")
    (macro SCE_H_SGML_COMMENT::long "SCE_H_SGML_COMMENT")
    (macro SCE_H_SGML_1ST_PARAM_COMMENT::long "SCE_H_SGML_1ST_PARAM_COMMENT")
    (macro SCE_H_SGML_BLOCK_DEFAULT::long "SCE_H_SGML_BLOCK_DEFAULT")
    (macro SCE_HJ_START::long "SCE_HJ_START")
    (macro SCE_HJ_DEFAULT::long "SCE_HJ_DEFAULT")
    (macro SCE_HJ_COMMENT::long "SCE_HJ_COMMENT")
    (macro SCE_HJ_COMMENTLINE::long "SCE_HJ_COMMENTLINE")
    (macro SCE_HJ_COMMENTDOC::long "SCE_HJ_COMMENTDOC")
    (macro SCE_HJ_NUMBER::long "SCE_HJ_NUMBER")
    (macro SCE_HJ_WORD::long "SCE_HJ_WORD")
    (macro SCE_HJ_KEYWORD::long "SCE_HJ_KEYWORD")
    (macro SCE_HJ_DOUBLESTRING::long "SCE_HJ_DOUBLESTRING")
    (macro SCE_HJ_SINGLESTRING::long "SCE_HJ_SINGLESTRING")
    (macro SCE_HJ_SYMBOLS::long "SCE_HJ_SYMBOLS")
    (macro SCE_HJ_STRINGEOL::long "SCE_HJ_STRINGEOL")
    (macro SCE_HJ_REGEX::long "SCE_HJ_REGEX")
    (macro SCE_HJA_START::long "SCE_HJA_START")
    (macro SCE_HJA_DEFAULT::long "SCE_HJA_DEFAULT")
    (macro SCE_HJA_COMMENT::long "SCE_HJA_COMMENT")
    (macro SCE_HJA_COMMENTLINE::long "SCE_HJA_COMMENTLINE")
    (macro SCE_HJA_COMMENTDOC::long "SCE_HJA_COMMENTDOC")
    (macro SCE_HJA_NUMBER::long "SCE_HJA_NUMBER")
    (macro SCE_HJA_WORD::long "SCE_HJA_WORD")
    (macro SCE_HJA_KEYWORD::long "SCE_HJA_KEYWORD")
    (macro SCE_HJA_DOUBLESTRING::long "SCE_HJA_DOUBLESTRING")
    (macro SCE_HJA_SINGLESTRING::long "SCE_HJA_SINGLESTRING")
    (macro SCE_HJA_SYMBOLS::long "SCE_HJA_SYMBOLS")
    (macro SCE_HJA_STRINGEOL::long "SCE_HJA_STRINGEOL")
    (macro SCE_HJA_REGEX::long "SCE_HJA_REGEX")
    (macro SCE_HB_START::long "SCE_HB_START")
    (macro SCE_HB_DEFAULT::long "SCE_HB_DEFAULT")
    (macro SCE_HB_COMMENTLINE::long "SCE_HB_COMMENTLINE")
    (macro SCE_HB_NUMBER::long "SCE_HB_NUMBER")
    (macro SCE_HB_WORD::long "SCE_HB_WORD")
    (macro SCE_HB_STRING::long "SCE_HB_STRING")
    (macro SCE_HB_IDENTIFIER::long "SCE_HB_IDENTIFIER")
    (macro SCE_HB_STRINGEOL::long "SCE_HB_STRINGEOL")
    (macro SCE_HBA_START::long "SCE_HBA_START")
    (macro SCE_HBA_DEFAULT::long "SCE_HBA_DEFAULT")
    (macro SCE_HBA_COMMENTLINE::long "SCE_HBA_COMMENTLINE")
    (macro SCE_HBA_NUMBER::long "SCE_HBA_NUMBER")
    (macro SCE_HBA_WORD::long "SCE_HBA_WORD")
    (macro SCE_HBA_STRING::long "SCE_HBA_STRING")
    (macro SCE_HBA_IDENTIFIER::long "SCE_HBA_IDENTIFIER")
    (macro SCE_HBA_STRINGEOL::long "SCE_HBA_STRINGEOL")
    (macro SCE_HP_START::long "SCE_HP_START")
    (macro SCE_HP_DEFAULT::long "SCE_HP_DEFAULT")
    (macro SCE_HP_COMMENTLINE::long "SCE_HP_COMMENTLINE")
    (macro SCE_HP_NUMBER::long "SCE_HP_NUMBER")
    (macro SCE_HP_STRING::long "SCE_HP_STRING")
    (macro SCE_HP_CHARACTER::long "SCE_HP_CHARACTER")
    (macro SCE_HP_WORD::long "SCE_HP_WORD")
    (macro SCE_HP_TRIPLE::long "SCE_HP_TRIPLE")
    (macro SCE_HP_TRIPLEDOUBLE::long "SCE_HP_TRIPLEDOUBLE")
    (macro SCE_HP_CLASSNAME::long "SCE_HP_CLASSNAME")
    (macro SCE_HP_DEFNAME::long "SCE_HP_DEFNAME")
    (macro SCE_HP_OPERATOR::long "SCE_HP_OPERATOR")
    (macro SCE_HP_IDENTIFIER::long "SCE_HP_IDENTIFIER")
    (macro SCE_HPA_START::long "SCE_HPA_START")
    (macro SCE_HPA_DEFAULT::long "SCE_HPA_DEFAULT")
    (macro SCE_HPA_COMMENTLINE::long "SCE_HPA_COMMENTLINE")
    (macro SCE_HPA_NUMBER::long "SCE_HPA_NUMBER")
    (macro SCE_HPA_STRING::long "SCE_HPA_STRING")
    (macro SCE_HPA_CHARACTER::long "SCE_HPA_CHARACTER")
    (macro SCE_HPA_WORD::long "SCE_HPA_WORD")
    (macro SCE_HPA_TRIPLE::long "SCE_HPA_TRIPLE")
    (macro SCE_HPA_TRIPLEDOUBLE::long "SCE_HPA_TRIPLEDOUBLE")
    (macro SCE_HPA_CLASSNAME::long "SCE_HPA_CLASSNAME")
    (macro SCE_HPA_DEFNAME::long "SCE_HPA_DEFNAME")
    (macro SCE_HPA_OPERATOR::long "SCE_HPA_OPERATOR")
    (macro SCE_HPA_IDENTIFIER::long "SCE_HPA_IDENTIFIER")
    (macro SCE_HPHP_DEFAULT::long "SCE_HPHP_DEFAULT")
    (macro SCE_HPHP_HSTRING::long "SCE_HPHP_HSTRING")
    (macro SCE_HPHP_SIMPLESTRING::long "SCE_HPHP_SIMPLESTRING")
    (macro SCE_HPHP_WORD::long "SCE_HPHP_WORD")
    (macro SCE_HPHP_NUMBER::long "SCE_HPHP_NUMBER")
    (macro SCE_HPHP_VARIABLE::long "SCE_HPHP_VARIABLE")
    (macro SCE_HPHP_COMMENT::long "SCE_HPHP_COMMENT")
    (macro SCE_HPHP_COMMENTLINE::long "SCE_HPHP_COMMENTLINE")
    (macro SCE_HPHP_HSTRING_VARIABLE::long "SCE_HPHP_HSTRING_VARIABLE")
    (macro SCE_HPHP_OPERATOR::long "SCE_HPHP_OPERATOR")
    (macro SCE_PL_DEFAULT::long "SCE_PL_DEFAULT")
    (macro SCE_PL_ERROR::long "SCE_PL_ERROR")
    (macro SCE_PL_COMMENTLINE::long "SCE_PL_COMMENTLINE")
    (macro SCE_PL_POD::long "SCE_PL_POD")
    (macro SCE_PL_NUMBER::long "SCE_PL_NUMBER")
    (macro SCE_PL_WORD::long "SCE_PL_WORD")
    (macro SCE_PL_STRING::long "SCE_PL_STRING")
    (macro SCE_PL_CHARACTER::long "SCE_PL_CHARACTER")
    (macro SCE_PL_PUNCTUATION::long "SCE_PL_PUNCTUATION")
    (macro SCE_PL_PREPROCESSOR::long "SCE_PL_PREPROCESSOR")
    (macro SCE_PL_OPERATOR::long "SCE_PL_OPERATOR")
    (macro SCE_PL_IDENTIFIER::long "SCE_PL_IDENTIFIER")
    (macro SCE_PL_SCALAR::long "SCE_PL_SCALAR")
    (macro SCE_PL_ARRAY::long "SCE_PL_ARRAY")
    (macro SCE_PL_HASH::long "SCE_PL_HASH")
    (macro SCE_PL_SYMBOLTABLE::long "SCE_PL_SYMBOLTABLE")
    (macro SCE_PL_REGEX::long "SCE_PL_REGEX")
    (macro SCE_PL_REGSUBST::long "SCE_PL_REGSUBST")
    (macro SCE_PL_LONGQUOTE::long "SCE_PL_LONGQUOTE")
    (macro SCE_PL_BACKTICKS::long "SCE_PL_BACKTICKS")
    (macro SCE_PL_DATASECTION::long "SCE_PL_DATASECTION")
    (macro SCE_PL_HERE_DELIM::long "SCE_PL_HERE_DELIM")
    (macro SCE_PL_HERE_Q::long "SCE_PL_HERE_Q")
    (macro SCE_PL_HERE_QQ::long "SCE_PL_HERE_QQ")
    (macro SCE_PL_HERE_QX::long "SCE_PL_HERE_QX")
    (macro SCE_PL_STRING_Q::long "SCE_PL_STRING_Q")
    (macro SCE_PL_STRING_QQ::long "SCE_PL_STRING_QQ")
    (macro SCE_PL_STRING_QX::long "SCE_PL_STRING_QX")
    (macro SCE_PL_STRING_QR::long "SCE_PL_STRING_QR")
    (macro SCE_PL_STRING_QW::long "SCE_PL_STRING_QW")
    (macro SCE_L_DEFAULT::long "SCE_L_DEFAULT")
    (macro SCE_L_COMMAND::long "SCE_L_COMMAND")
    (macro SCE_L_TAG::long "SCE_L_TAG")
    (macro SCE_L_MATH::long "SCE_L_MATH")
    (macro SCE_L_COMMENT::long "SCE_L_COMMENT")
    (macro SCE_LUA_DEFAULT::long "SCE_LUA_DEFAULT")
    (macro SCE_LUA_COMMENT::long "SCE_LUA_COMMENT")
    (macro SCE_LUA_COMMENTLINE::long "SCE_LUA_COMMENTLINE")
    (macro SCE_LUA_COMMENTDOC::long "SCE_LUA_COMMENTDOC")
    (macro SCE_LUA_NUMBER::long "SCE_LUA_NUMBER")
    (macro SCE_LUA_WORD::long "SCE_LUA_WORD")
    (macro SCE_LUA_STRING::long "SCE_LUA_STRING")
    (macro SCE_LUA_CHARACTER::long "SCE_LUA_CHARACTER")
    (macro SCE_LUA_LITERALSTRING::long "SCE_LUA_LITERALSTRING")
    (macro SCE_LUA_PREPROCESSOR::long "SCE_LUA_PREPROCESSOR")
    (macro SCE_LUA_OPERATOR::long "SCE_LUA_OPERATOR")
    (macro SCE_LUA_IDENTIFIER::long "SCE_LUA_IDENTIFIER")
    (macro SCE_LUA_STRINGEOL::long "SCE_LUA_STRINGEOL")
    (macro SCE_ERR_DEFAULT::long "SCE_ERR_DEFAULT")
    (macro SCE_ERR_PYTHON::long "SCE_ERR_PYTHON")
    (macro SCE_ERR_GCC::long "SCE_ERR_GCC")
    (macro SCE_ERR_MS::long "SCE_ERR_MS")
    (macro SCE_ERR_CMD::long "SCE_ERR_CMD")
    (macro SCE_ERR_BORLAND::long "SCE_ERR_BORLAND")
    (macro SCE_ERR_PERL::long "SCE_ERR_PERL")
    (macro SCE_ERR_NET::long "SCE_ERR_NET")
    (macro SCE_ERR_LUA::long "SCE_ERR_LUA")
    (macro SCE_ERR_DIFF_CHANGED::long "SCE_ERR_DIFF_CHANGED")
    (macro SCE_ERR_DIFF_ADDITION::long "SCE_ERR_DIFF_ADDITION")
    (macro SCE_ERR_DIFF_DELETION::long "SCE_ERR_DIFF_DELETION")
    (macro SCE_ERR_DIFF_MESSAGE::long "SCE_ERR_DIFF_MESSAGE")
    (macro SCE_BAT_DEFAULT::long "SCE_BAT_DEFAULT")
    (macro SCE_BAT_COMMENT::long "SCE_BAT_COMMENT")
    (macro SCE_BAT_WORD::long "SCE_BAT_WORD")
    (macro SCE_BAT_LABEL::long "SCE_BAT_LABEL")
    (macro SCE_BAT_HIDE::long "SCE_BAT_HIDE")
    (macro SCE_BAT_COMMAND::long "SCE_BAT_COMMAND")
    (macro SCE_BAT_IDENTIFIER::long "SCE_BAT_IDENTIFIER")
    (macro SCE_BAT_OPERATOR::long "SCE_BAT_OPERATOR")
    (macro SCE_MAKE_DEFAULT::long "SCE_MAKE_DEFAULT")
    (macro SCE_MAKE_COMMENT::long "SCE_MAKE_COMMENT")
    (macro SCE_MAKE_PREPROCESSOR::long "SCE_MAKE_PREPROCESSOR")
    (macro SCE_MAKE_IDENTIFIER::long "SCE_MAKE_IDENTIFIER")
    (macro SCE_MAKE_OPERATOR::long "SCE_MAKE_OPERATOR")
    (macro SCE_MAKE_TARGET::long "SCE_MAKE_TARGET")
    (macro SCE_MAKE_IDEOL::long "SCE_MAKE_IDEOL")
    (macro SCE_CONF_DEFAULT::long "SCE_CONF_DEFAULT")
    (macro SCE_CONF_COMMENT::long "SCE_CONF_COMMENT")
    (macro SCE_CONF_NUMBER::long "SCE_CONF_NUMBER")
    (macro SCE_CONF_IDENTIFIER::long "SCE_CONF_IDENTIFIER")
    (macro SCE_CONF_EXTENSION::long "SCE_CONF_EXTENSION")
    (macro SCE_CONF_PARAMETER::long "SCE_CONF_PARAMETER")
    (macro SCE_CONF_STRING::long "SCE_CONF_STRING")
    (macro SCE_CONF_OPERATOR::long "SCE_CONF_OPERATOR")
    (macro SCE_CONF_IP::long "SCE_CONF_IP")
    (macro SCE_CONF_DIRECTIVE::long "SCE_CONF_DIRECTIVE")
    (macro SCE_AVE_DEFAULT::long "SCE_AVE_DEFAULT")
    (macro SCE_AVE_COMMENT::long "SCE_AVE_COMMENT")
    (macro SCE_AVE_NUMBER::long "SCE_AVE_NUMBER")
    (macro SCE_AVE_WORD::long "SCE_AVE_WORD")
    (macro SCE_AVE_KEYWORD::long "SCE_AVE_KEYWORD")
    (macro SCE_AVE_STATEMENT::long "SCE_AVE_STATEMENT")
    (macro SCE_AVE_STRING::long "SCE_AVE_STRING")
    (macro SCE_AVE_ENUM::long "SCE_AVE_ENUM")
    (macro SCE_AVE_STRINGEOL::long "SCE_AVE_STRINGEOL")
    (macro SCE_AVE_IDENTIFIER::long "SCE_AVE_IDENTIFIER")
    (macro SCE_AVE_OPERATOR::long "SCE_AVE_OPERATOR")
    (macro SCE_ADA_DEFAULT::long "SCE_ADA_DEFAULT")
    (macro SCE_ADA_COMMENT::long "SCE_ADA_COMMENT")
    (macro SCE_ADA_NUMBER::long "SCE_ADA_NUMBER")
    (macro SCE_ADA_WORD::long "SCE_ADA_WORD")
    (macro SCE_ADA_STRING::long "SCE_ADA_STRING")
    (macro SCE_ADA_CHARACTER::long "SCE_ADA_CHARACTER")
    (macro SCE_ADA_OPERATOR::long "SCE_ADA_OPERATOR")
    (macro SCE_ADA_IDENTIFIER::long "SCE_ADA_IDENTIFIER")
    (macro SCE_ADA_STRINGEOL::long "SCE_ADA_STRINGEOL")
    (macro SCE_BAAN_DEFAULT::long "SCE_BAAN_DEFAULT")
    (macro SCE_BAAN_COMMENT::long "SCE_BAAN_COMMENT")
    (macro SCE_BAAN_COMMENTDOC::long "SCE_BAAN_COMMENTDOC")
    (macro SCE_BAAN_NUMBER::long "SCE_BAAN_NUMBER")
    (macro SCE_BAAN_WORD::long "SCE_BAAN_WORD")
    (macro SCE_BAAN_STRING::long "SCE_BAAN_STRING")
    (macro SCE_BAAN_PREPROCESSOR::long "SCE_BAAN_PREPROCESSOR")
    (macro SCE_BAAN_OPERATOR::long "SCE_BAAN_OPERATOR")
    (macro SCE_BAAN_IDENTIFIER::long "SCE_BAAN_IDENTIFIER")
    (macro SCE_BAAN_STRINGEOL::long "SCE_BAAN_STRINGEOL")
    (macro SCE_BAAN_WORD2::long "SCE_BAAN_WORD2")
    (macro SCE_LISP_DEFAULT::long "SCE_LISP_DEFAULT")
    (macro SCE_LISP_COMMENT::long "SCE_LISP_COMMENT")
    (macro SCE_LISP_NUMBER::long "SCE_LISP_NUMBER")
    (macro SCE_LISP_KEYWORD::long "SCE_LISP_KEYWORD")
    (macro SCE_LISP_STRING::long "SCE_LISP_STRING")
    (macro SCE_LISP_STRINGEOL::long "SCE_LISP_STRINGEOL")
    (macro SCE_LISP_IDENTIFIER::long "SCE_LISP_IDENTIFIER")
    (macro SCE_LISP_OPERATOR::long "SCE_LISP_OPERATOR")
    (macro SCE_EIFFEL_DEFAULT::long "SCE_EIFFEL_DEFAULT")
    (macro SCE_EIFFEL_COMMENTLINE::long "SCE_EIFFEL_COMMENTLINE")
    (macro SCE_EIFFEL_NUMBER::long "SCE_EIFFEL_NUMBER")
    (macro SCE_EIFFEL_WORD::long "SCE_EIFFEL_WORD")
    (macro SCE_EIFFEL_STRING::long "SCE_EIFFEL_STRING")
    (macro SCE_EIFFEL_CHARACTER::long "SCE_EIFFEL_CHARACTER")
    (macro SCE_EIFFEL_OPERATOR::long "SCE_EIFFEL_OPERATOR")
    (macro SCE_EIFFEL_IDENTIFIER::long "SCE_EIFFEL_IDENTIFIER")
    (macro SCE_EIFFEL_STRINGEOL::long "SCE_EIFFEL_STRINGEOL")
    (macro SCE_NNCRONTAB_DEFAULT::long "SCE_NNCRONTAB_DEFAULT")
    (macro SCE_NNCRONTAB_COMMENT::long "SCE_NNCRONTAB_COMMENT")
    (macro SCE_NNCRONTAB_TASK::long "SCE_NNCRONTAB_TASK")
    (macro SCE_NNCRONTAB_SECTION::long "SCE_NNCRONTAB_SECTION")
    (macro SCE_NNCRONTAB_KEYWORD::long "SCE_NNCRONTAB_KEYWORD")
    (macro SCE_NNCRONTAB_MODIFIER::long "SCE_NNCRONTAB_MODIFIER")
    (macro SCE_NNCRONTAB_ASTERISK::long "SCE_NNCRONTAB_ASTERISK")
    (macro SCE_NNCRONTAB_NUMBER::long "SCE_NNCRONTAB_NUMBER")
    (macro SCE_NNCRONTAB_STRING::long "SCE_NNCRONTAB_STRING")
    (macro SCE_NNCRONTAB_ENVIRONMENT::long "SCE_NNCRONTAB_ENVIRONMENT")
    (macro SCE_NNCRONTAB_IDENTIFIER::long "SCE_NNCRONTAB_IDENTIFIER")
    (macro gtk_scintilla_get_type::guint () "gtk_scintilla_get_type")
    (macro gtk_scintilla_new::GtkWidget* () "gtk_scintilla_new")
    (macro gtk_scintilla_find_text::long (GtkScintilla* int string long long long* long*) "gtk_scintilla_find_text")
    (macro gtk_scintilla_add_text::void (GtkScintilla* int string) "gtk_scintilla_add_text")
    (macro gtk_scintilla_insert_text::void (GtkScintilla* long string) "gtk_scintilla_insert_text")
    (macro gtk_scintilla_clear_all::void (GtkScintilla*) "gtk_scintilla_clear_all")
    (macro gtk_scintilla_clear_document_style::void (GtkScintilla*) "gtk_scintilla_clear_document_style")
    (macro gtk_scintilla_get_length::int (GtkScintilla*) "gtk_scintilla_get_length")
    (macro gtk_scintilla_get_char_at::int (GtkScintilla* long) "gtk_scintilla_get_char_at")
    (macro gtk_scintilla_get_current_pos::long (GtkScintilla*) "gtk_scintilla_get_current_pos")
    (macro gtk_scintilla_get_anchor::long (GtkScintilla*) "gtk_scintilla_get_anchor")
    (macro gtk_scintilla_get_style_at::int (GtkScintilla* long) "gtk_scintilla_get_style_at")
    (macro gtk_scintilla_redo::void (GtkScintilla*) "gtk_scintilla_redo")
    (macro gtk_scintilla_set_undo_collection::void (GtkScintilla* int) "gtk_scintilla_set_undo_collection")
    (macro gtk_scintilla_select_all::void (GtkScintilla*) "gtk_scintilla_select_all")
    (macro gtk_scintilla_set_save_point::void (GtkScintilla*) "gtk_scintilla_set_save_point")
    (macro gtk_scintilla_can_redo::int (GtkScintilla*) "gtk_scintilla_can_redo")
    (macro gtk_scintilla_marker_line_from_handle::int (GtkScintilla* int) "gtk_scintilla_marker_line_from_handle")
    (macro gtk_scintilla_marker_delete_handle::void (GtkScintilla* int) "gtk_scintilla_marker_delete_handle")
    (macro gtk_scintilla_get_undo_collection::int (GtkScintilla*) "gtk_scintilla_get_undo_collection")
    (macro gtk_scintilla_get_view_ws::int (GtkScintilla*) "gtk_scintilla_get_view_ws")
    (macro gtk_scintilla_set_view_ws::void (GtkScintilla* int) "gtk_scintilla_set_view_ws")
    (macro gtk_scintilla_position_from_point::int (GtkScintilla* int int) "gtk_scintilla_position_from_point")
    (macro gtk_scintilla_position_from_point_close::int (GtkScintilla* int int) "gtk_scintilla_position_from_point_close")
    (macro gtk_scintilla_goto_line::void (GtkScintilla* int) "gtk_scintilla_goto_line")
    (macro gtk_scintilla_goto_pos::void (GtkScintilla* long) "gtk_scintilla_goto_pos")
    (macro gtk_scintilla_set_anchor::void (GtkScintilla* long) "gtk_scintilla_set_anchor")
    (macro gtk_scintilla_get_cur_line::int (GtkScintilla* int string) "gtk_scintilla_get_cur_line")
    (macro gtk_scintilla_get_end_styled::long (GtkScintilla*) "gtk_scintilla_get_end_styled")
    (macro gtk_scintilla_convert_eols::void (GtkScintilla* int) "gtk_scintilla_convert_eols")
    (macro gtk_scintilla_get_eol_mode::int (GtkScintilla*) "gtk_scintilla_get_eol_mode")
    (macro gtk_scintilla_set_eol_mode::void (GtkScintilla* int) "gtk_scintilla_set_eol_mode")
    (macro gtk_scintilla_start_styling::void (GtkScintilla* long int) "gtk_scintilla_start_styling")
    (macro gtk_scintilla_set_styling::void (GtkScintilla* int int) "gtk_scintilla_set_styling")
    (macro gtk_scintilla_get_buffered_draw::int (GtkScintilla*) "gtk_scintilla_get_buffered_draw")
    (macro gtk_scintilla_set_buffered_draw::void (GtkScintilla* int) "gtk_scintilla_set_buffered_draw")
    (macro gtk_scintilla_set_tab_width::void (GtkScintilla* int) "gtk_scintilla_set_tab_width")
    (macro gtk_scintilla_get_tab_width::int (GtkScintilla*) "gtk_scintilla_get_tab_width")
    (macro gtk_scintilla_set_code_page::void (GtkScintilla* int) "gtk_scintilla_set_code_page")
    (macro gtk_scintilla_set_use_palette::void (GtkScintilla* int) "gtk_scintilla_set_use_palette")
    (macro gtk_scintilla_marker_define::void (GtkScintilla* int int) "gtk_scintilla_marker_define")
    (macro gtk_scintilla_marker_set_fore::void (GtkScintilla* int long) "gtk_scintilla_marker_set_fore")
    (macro gtk_scintilla_marker_set_back::void (GtkScintilla* int long) "gtk_scintilla_marker_set_back")
    (macro gtk_scintilla_marker_add::int (GtkScintilla* int int) "gtk_scintilla_marker_add")
    (macro gtk_scintilla_marker_delete::void (GtkScintilla* int int) "gtk_scintilla_marker_delete")
    (macro gtk_scintilla_marker_delete_all::void (GtkScintilla* int) "gtk_scintilla_marker_delete_all")
    (macro gtk_scintilla_marker_get::int (GtkScintilla* int) "gtk_scintilla_marker_get")
    (macro gtk_scintilla_marker_next::int (GtkScintilla* int int) "gtk_scintilla_marker_next")
    (macro gtk_scintilla_marker_previous::int (GtkScintilla* int int) "gtk_scintilla_marker_previous")
    (macro gtk_scintilla_set_margin_type_n::void (GtkScintilla* int int) "gtk_scintilla_set_margin_type_n")
    (macro gtk_scintilla_get_margin_type_n::int (GtkScintilla* int) "gtk_scintilla_get_margin_type_n")
    (macro gtk_scintilla_set_margin_width_n::void (GtkScintilla* int int) "gtk_scintilla_set_margin_width_n")
    (macro gtk_scintilla_get_margin_width_n::int (GtkScintilla* int) "gtk_scintilla_get_margin_width_n")
    (macro gtk_scintilla_set_margin_mask_n::void (GtkScintilla* int int) "gtk_scintilla_set_margin_mask_n")
    (macro gtk_scintilla_get_margin_mask_n::int (GtkScintilla* int) "gtk_scintilla_get_margin_mask_n")
    (macro gtk_scintilla_set_margin_sensitive_n::void (GtkScintilla* int int) "gtk_scintilla_set_margin_sensitive_n")
    (macro gtk_scintilla_get_margin_sensitive_n::int (GtkScintilla* int) "gtk_scintilla_get_margin_sensitive_n")
    (macro gtk_scintilla_style_clear_all::void (GtkScintilla*) "gtk_scintilla_style_clear_all")
    (macro gtk_scintilla_style_set_fore::void (GtkScintilla* int long) "gtk_scintilla_style_set_fore")
   (macro gtk_scintilla_style_set_back::void (GtkScintilla* int long) "gtk_scintilla_style_set_back")
    (macro gtk_scintilla_style_set_bold::void (GtkScintilla* int int) "gtk_scintilla_style_set_bold")
    (macro gtk_scintilla_style_set_italic::void (GtkScintilla* int int) "gtk_scintilla_style_set_italic")
    (macro gtk_scintilla_style_set_size::void (GtkScintilla* int int) "gtk_scintilla_style_set_size")
    (macro gtk_scintilla_style_set_font::void (GtkScintilla* int string) "gtk_scintilla_style_set_font")
    (macro gtk_scintilla_style_set_eol_filled::void (GtkScintilla* int int) "gtk_scintilla_style_set_eol_filled")
    (macro gtk_scintilla_style_reset_default::void (GtkScintilla*) "gtk_scintilla_style_reset_default")
    (macro gtk_scintilla_style_set_underline::void (GtkScintilla* int int) "gtk_scintilla_style_set_underline")
    (macro gtk_scintilla_style_set_case::void (GtkScintilla* int int) "gtk_scintilla_style_set_case")
    (macro gtk_scintilla_style_set_character_set::void (GtkScintilla* int int) "gtk_scintilla_style_set_character_set")
    (macro gtk_scintilla_set_sel_fore::void (GtkScintilla* int long) "gtk_scintilla_set_sel_fore")
    (macro gtk_scintilla_set_sel_back::void (GtkScintilla* int long) "gtk_scintilla_set_sel_back")
    (macro gtk_scintilla_set_caret_fore::void (GtkScintilla* long) "gtk_scintilla_set_caret_fore")
    (macro gtk_scintilla_clear_all_cmd_keys::void (GtkScintilla*) "gtk_scintilla_clear_all_cmd_keys")
    (macro gtk_scintilla_set_styling_ex::void (GtkScintilla* int string) "gtk_scintilla_set_styling_ex")
    (macro gtk_scintilla_style_set_visible::void (GtkScintilla* int int) "gtk_scintilla_style_set_visible")
    (macro gtk_scintilla_get_caret_period::int (GtkScintilla*) "gtk_scintilla_get_caret_period")
    (macro gtk_scintilla_set_caret_period::void (GtkScintilla* int) "gtk_scintilla_set_caret_period")
    (macro gtk_scintilla_set_word_chars::void (GtkScintilla* string) "gtk_scintilla_set_word_chars")
    (macro gtk_scintilla_begin_undo_action::void (GtkScintilla*) "gtk_scintilla_begin_undo_action")
    (macro gtk_scintilla_end_undo_action::void (GtkScintilla*) "gtk_scintilla_end_undo_action")
    (macro gtk_scintilla_indic_set_style::void (GtkScintilla* int int) "gtk_scintilla_indic_set_style")
    (macro gtk_scintilla_indic_get_style::int (GtkScintilla* int) "gtk_scintilla_indic_get_style")
    (macro gtk_scintilla_indic_set_fore::void (GtkScintilla* int long) "gtk_scintilla_indic_set_fore")
    (macro gtk_scintilla_indic_get_fore::long (GtkScintilla* int) "gtk_scintilla_indic_get_fore")
    (macro gtk_scintilla_set_style_bits::void (GtkScintilla* int) "gtk_scintilla_set_style_bits")
    (macro gtk_scintilla_get_style_bits::int (GtkScintilla*) "gtk_scintilla_get_style_bits")
    (macro gtk_scintilla_set_line_state::void (GtkScintilla* int int) "gtk_scintilla_set_line_state")
    (macro gtk_scintilla_get_line_state::int (GtkScintilla* int) "gtk_scintilla_get_line_state")
    (macro gtk_scintilla_get_max_line_state::int (GtkScintilla*) "gtk_scintilla_get_max_line_state")
    (macro gtk_scintilla_get_caret_line_visible::int (GtkScintilla*) "gtk_scintilla_get_caret_line_visible")
    (macro gtk_scintilla_set_caret_line_visible::void (GtkScintilla* int) "gtk_scintilla_set_caret_line_visible")
    (macro gtk_scintilla_get_caret_line_back::long (GtkScintilla*) "gtk_scintilla_get_caret_line_back")
    (macro gtk_scintilla_set_caret_line_back::void (GtkScintilla* long) "gtk_scintilla_set_caret_line_back")
    (macro gtk_scintilla_style_set_changeable::void (GtkScintilla* int int) "gtk_scintilla_style_set_changeable")
    (macro gtk_scintilla_autoc_show::void (GtkScintilla* int string) "gtk_scintilla_autoc_show")
    (macro gtk_scintilla_autoc_cancel::void (GtkScintilla*) "gtk_scintilla_autoc_cancel")
    (macro gtk_scintilla_autoc_active::int (GtkScintilla*) "gtk_scintilla_autoc_active")
    (macro gtk_scintilla_autoc_pos_start::long (GtkScintilla*) "gtk_scintilla_autoc_pos_start")
    (macro gtk_scintilla_autoc_complete::void (GtkScintilla*) "gtk_scintilla_autoc_complete")
    (macro gtk_scintilla_autoc_stops::void (GtkScintilla* string) "gtk_scintilla_autoc_stops")
    (macro gtk_scintilla_autoc_set_separator::void (GtkScintilla* int) "gtk_scintilla_autoc_set_separator")
    (macro gtk_scintilla_autoc_get_separator::int (GtkScintilla*) "gtk_scintilla_autoc_get_separator")
    (macro gtk_scintilla_autoc_select::void (GtkScintilla* string) "gtk_scintilla_autoc_select")
    (macro gtk_scintilla_autoc_set_cancel_at_start::void (GtkScintilla* int) "gtk_scintilla_autoc_set_cancel_at_start")
    (macro gtk_scintilla_autoc_get_cancel_at_start::int (GtkScintilla*) "gtk_scintilla_autoc_get_cancel_at_start")
    (macro gtk_scintilla_autoc_set_fill_ups::void (GtkScintilla* string) "gtk_scintilla_autoc_set_fill_ups")
    (macro gtk_scintilla_autoc_set_choose_single::void (GtkScintilla* int) "gtk_scintilla_autoc_set_choose_single")
    (macro gtk_scintilla_autoc_get_choose_single::int (GtkScintilla*) "gtk_scintilla_autoc_get_choose_single")
    (macro gtk_scintilla_autoc_set_ignore_case::void (GtkScintilla* int) "gtk_scintilla_autoc_set_ignore_case")
    (macro gtk_scintilla_autoc_get_ignore_case::int (GtkScintilla*) "gtk_scintilla_autoc_get_ignore_case")
    (macro gtk_scintilla_user_list_show::void (GtkScintilla* int string) "gtk_scintilla_user_list_show")
    (macro gtk_scintilla_autoc_set_auto_hide::void (GtkScintilla* int) "gtk_scintilla_autoc_set_auto_hide")
    (macro gtk_scintilla_autoc_get_auto_hide::int (GtkScintilla*) "gtk_scintilla_autoc_get_auto_hide")
    (macro gtk_scintilla_autoc_set_drop_rest_of_word::void (GtkScintilla* int) "gtk_scintilla_autoc_set_drop_rest_of_word")
    (macro gtk_scintilla_autoc_get_drop_rest_of_word::int (GtkScintilla*) "gtk_scintilla_autoc_get_drop_rest_of_word")
    (macro gtk_scintilla_set_indent::void (GtkScintilla* int) "gtk_scintilla_set_indent")
    (macro gtk_scintilla_get_indent::int (GtkScintilla*) "gtk_scintilla_get_indent")
    (macro gtk_scintilla_set_use_tabs::void (GtkScintilla* int) "gtk_scintilla_set_use_tabs")
    (macro gtk_scintilla_get_use_tabs::int (GtkScintilla*) "gtk_scintilla_get_use_tabs")
    (macro gtk_scintilla_set_line_indentation::void (GtkScintilla* int int) "gtk_scintilla_set_line_indentation")
    (macro gtk_scintilla_get_line_indentation::int (GtkScintilla* int) "gtk_scintilla_get_line_indentation")
    (macro gtk_scintilla_get_line_indent_position::long (GtkScintilla* int) "gtk_scintilla_get_line_indent_position")
    (macro gtk_scintilla_get_column::int (GtkScintilla* long) "gtk_scintilla_get_column")
    (macro gtk_scintilla_set_h_scroll_bar::void (GtkScintilla* int) "gtk_scintilla_set_h_scroll_bar")
    (macro gtk_scintilla_get_h_scroll_bar::int (GtkScintilla*) "gtk_scintilla_get_h_scroll_bar")
    (macro gtk_scintilla_set_indentation_guides::void (GtkScintilla* int) "gtk_scintilla_set_indentation_guides")
    (macro gtk_scintilla_get_indentation_guides::int (GtkScintilla*) "gtk_scintilla_get_indentation_guides")
    (macro gtk_scintilla_set_highlight_guide::void (GtkScintilla* int) "gtk_scintilla_set_highlight_guide")
    (macro gtk_scintilla_get_highlight_guide::int (GtkScintilla*) "gtk_scintilla_get_highlight_guide")
    (macro gtk_scintilla_get_line_end_position::int (GtkScintilla* int) "gtk_scintilla_get_line_end_position")
    (macro gtk_scintilla_get_code_page::int (GtkScintilla*) "gtk_scintilla_get_code_page")
    (macro gtk_scintilla_get_caret_fore::long (GtkScintilla*) "gtk_scintilla_get_caret_fore")
    (macro gtk_scintilla_get_use_palette::int (GtkScintilla*) "gtk_scintilla_get_use_palette")
    (macro gtk_scintilla_get_read_only::int (GtkScintilla*) "gtk_scintilla_get_read_only")
    (macro gtk_scintilla_set_current_pos::void (GtkScintilla* long) "gtk_scintilla_set_current_pos")
    (macro gtk_scintilla_set_selection_start::void (GtkScintilla* long) "gtk_scintilla_set_selection_start")
    (macro gtk_scintilla_get_selection_start::long (GtkScintilla*) "gtk_scintilla_get_selection_start")
    (macro gtk_scintilla_set_selection_end::void (GtkScintilla* long) "gtk_scintilla_set_selection_end")
    (macro gtk_scintilla_get_selection_end::long (GtkScintilla*) "gtk_scintilla_get_selection_end")
    (macro gtk_scintilla_set_print_magnification::void (GtkScintilla* int) "gtk_scintilla_set_print_magnification")
    (macro gtk_scintilla_get_print_magnification::int (GtkScintilla*) "gtk_scintilla_get_print_magnification")
    (macro gtk_scintilla_set_print_colour_mode::void (GtkScintilla* int) "gtk_scintilla_set_print_colour_mode")
    (macro gtk_scintilla_get_print_colour_mode::int (GtkScintilla*) "gtk_scintilla_get_print_colour_mode")
    (macro gtk_scintilla_get_first_visible_line::int (GtkScintilla*) "gtk_scintilla_get_first_visible_line")
    (macro gtk_scintilla_get_line::int (GtkScintilla* int string) "gtk_scintilla_get_line")
    (macro gtk_scintilla_get_line_count::int (GtkScintilla*) "gtk_scintilla_get_line_count")
    (macro gtk_scintilla_set_margin_left::void (GtkScintilla* int) "gtk_scintilla_set_margin_left")
    (macro gtk_scintilla_get_margin_left::int (GtkScintilla*) "gtk_scintilla_get_margin_left")
    (macro gtk_scintilla_set_margin_right::void (GtkScintilla* int) "gtk_scintilla_set_margin_right")
    (macro gtk_scintilla_get_margin_right::int (GtkScintilla*) "gtk_scintilla_get_margin_right")
    (macro gtk_scintilla_get_modify::int (GtkScintilla*) "gtk_scintilla_get_modify")
    (macro gtk_scintilla_set_sel::void (GtkScintilla* long long) "gtk_scintilla_set_sel")
    (macro gtk_scintilla_get_sel_text::int (GtkScintilla* string) "gtk_scintilla_get_sel_text")
    (macro gtk_scintilla_hide_selection::void (GtkScintilla* int) "gtk_scintilla_hide_selection")
    (macro gtk_scintilla_point_x_from_position::int (GtkScintilla* long) "gtk_scintilla_point_x_from_position")
    (macro gtk_scintilla_point_y_from_position::int (GtkScintilla* long) "gtk_scintilla_point_y_from_position")
    (macro gtk_scintilla_line_from_position::int (GtkScintilla* long) "gtk_scintilla_line_from_position")
    (macro gtk_scintilla_position_from_line::int (GtkScintilla* int) "gtk_scintilla_position_from_line")
    (macro gtk_scintilla_line_scroll::void (GtkScintilla* int int) "gtk_scintilla_line_scroll")
    (macro gtk_scintilla_scroll_caret::void (GtkScintilla*) "gtk_scintilla_scroll_caret")
    (macro gtk_scintilla_replace_sel::void (GtkScintilla* string) "gtk_scintilla_replace_sel")
    (macro gtk_scintilla_set_read_only::void (GtkScintilla* int) "gtk_scintilla_set_read_only")
    (macro gtk_scintilla_null::void (GtkScintilla*) "gtk_scintilla_null")
    (macro gtk_scintilla_can_paste::int (GtkScintilla*) "gtk_scintilla_can_paste")
    (macro gtk_scintilla_can_undo::int (GtkScintilla*) "gtk_scintilla_can_undo")
    (macro gtk_scintilla_empty_undo_buffer::void (GtkScintilla*) "gtk_scintilla_empty_undo_buffer")
    (macro gtk_scintilla_undo::void (GtkScintilla*) "gtk_scintilla_undo")
    (macro gtk_scintilla_cut::void (GtkScintilla*) "gtk_scintilla_cut")
    (macro gtk_scintilla_copy::void (GtkScintilla*) "gtk_scintilla_copy")
    (macro gtk_scintilla_paste::void (GtkScintilla*) "gtk_scintilla_paste")
    (macro gtk_scintilla_clear::void (GtkScintilla*) "gtk_scintilla_clear")
    (macro gtk_scintilla_set_text::void (GtkScintilla* string) "gtk_scintilla_set_text")
    (macro gtk_scintilla_get_text::int (GtkScintilla* int string) "gtk_scintilla_get_text")
    (macro gtk_scintilla_get_text_length::int (GtkScintilla*) "gtk_scintilla_get_text_length")
    (macro gtk_scintilla_get_direct_function::int (GtkScintilla*) "gtk_scintilla_get_direct_function")
    (macro gtk_scintilla_get_direct_pointer::int (GtkScintilla*) "gtk_scintilla_get_direct_pointer")
    (macro gtk_scintilla_set_overtype::void (GtkScintilla* int) "gtk_scintilla_set_overtype")
    (macro gtk_scintilla_get_overtype::int (GtkScintilla*) "gtk_scintilla_get_overtype")
    (macro gtk_scintilla_set_caret_width::void (GtkScintilla* int) "gtk_scintilla_set_caret_width")
    (macro gtk_scintilla_get_caret_width::int (GtkScintilla*) "gtk_scintilla_get_caret_width")
    (macro gtk_scintilla_set_target_start::void (GtkScintilla* long) "gtk_scintilla_set_target_start")
    (macro gtk_scintilla_get_target_start::long (GtkScintilla*) "gtk_scintilla_get_target_start")
    (macro gtk_scintilla_set_target_end::void (GtkScintilla* long) "gtk_scintilla_set_target_end")
    (macro gtk_scintilla_get_target_end::long (GtkScintilla*) "gtk_scintilla_get_target_end")
    (macro gtk_scintilla_replace_target::int (GtkScintilla* int string) "gtk_scintilla_replace_target")
    (macro gtk_scintilla_replace_target_re::int (GtkScintilla* int string) "gtk_scintilla_replace_target_re")
    (macro gtk_scintilla_search_in_target::int (GtkScintilla* int string) "gtk_scintilla_search_in_target")
    (macro gtk_scintilla_set_search_flags::void (GtkScintilla* int) "gtk_scintilla_set_search_flags")
    (macro gtk_scintilla_get_search_flags::int (GtkScintilla*) "gtk_scintilla_get_search_flags")
    (macro gtk_scintilla_call_tip_show::void (GtkScintilla* long string) "gtk_scintilla_call_tip_show")
    (macro gtk_scintilla_call_tip_cancel::void (GtkScintilla*) "gtk_scintilla_call_tip_cancel")
    (macro gtk_scintilla_call_tip_active::int (GtkScintilla*) "gtk_scintilla_call_tip_active")
    (macro gtk_scintilla_call_tip_pos_start::long (GtkScintilla*) "gtk_scintilla_call_tip_pos_start")
    (macro gtk_scintilla_call_tip_set_hlt::void (GtkScintilla* int int) "gtk_scintilla_call_tip_set_hlt")
    (macro gtk_scintilla_call_tip_set_back::void (GtkScintilla* long) "gtk_scintilla_call_tip_set_back")
    (macro gtk_scintilla_visible_from_doc_line::int (GtkScintilla* int) "gtk_scintilla_visible_from_doc_line")
    (macro gtk_scintilla_doc_line_from_visible::int (GtkScintilla* int) "gtk_scintilla_doc_line_from_visible")
    (macro gtk_scintilla_set_fold_level::void (GtkScintilla* int int) "gtk_scintilla_set_fold_level")
    (macro gtk_scintilla_get_fold_level::int (GtkScintilla* int) "gtk_scintilla_get_fold_level")
    (macro gtk_scintilla_get_last_child::int (GtkScintilla* int int) "gtk_scintilla_get_last_child")
    (macro gtk_scintilla_get_fold_parent::int (GtkScintilla* int) "gtk_scintilla_get_fold_parent")
    (macro gtk_scintilla_show_lines::void (GtkScintilla* int int) "gtk_scintilla_show_lines")
    (macro gtk_scintilla_hide_lines::void (GtkScintilla* int int) "gtk_scintilla_hide_lines")
    (macro gtk_scintilla_get_line_visible::int (GtkScintilla* int) "gtk_scintilla_get_line_visible")
    (macro gtk_scintilla_set_fold_expanded::void (GtkScintilla* int int) "gtk_scintilla_set_fold_expanded")
    (macro gtk_scintilla_get_fold_expanded::int (GtkScintilla* int) "gtk_scintilla_get_fold_expanded")
    (macro gtk_scintilla_toggle_fold::void (GtkScintilla* int) "gtk_scintilla_toggle_fold")
    (macro gtk_scintilla_ensure_visible::void (GtkScintilla* int) "gtk_scintilla_ensure_visible")
    (macro gtk_scintilla_set_fold_flags::void (GtkScintilla* int) "gtk_scintilla_set_fold_flags")
    (macro gtk_scintilla_ensure_visible_enforce_policy::void (GtkScintilla* int) "gtk_scintilla_ensure_visible_enforce_policy")
    (macro gtk_scintilla_set_tab_indents::void (GtkScintilla* int) "gtk_scintilla_set_tab_indents")
    (macro gtk_scintilla_get_tab_indents::int (GtkScintilla*) "gtk_scintilla_get_tab_indents")
    (macro gtk_scintilla_set_backspace_unindents::void (GtkScintilla* int) "gtk_scintilla_set_backspace_unindents")
    (macro gtk_scintilla_get_backspace_unindents::int (GtkScintilla*) "gtk_scintilla_get_backspace_unindents")
    (macro gtk_scintilla_set_mouse_dwell_time::void (GtkScintilla* int) "gtk_scintilla_set_mouse_dwell_time")
    (macro gtk_scintilla_get_mouse_dwell_time::int (GtkScintilla*) "gtk_scintilla_get_mouse_dwell_time")
    (macro gtk_scintilla_word_start_position::int (GtkScintilla* long) "gtk_scintilla_word_start_position")
    (macro gtk_scintilla_word_end_position::int (GtkScintilla* long) "gtk_scintilla_word_end_position")
    (macro gtk_scintilla_set_wrap_mode::void (GtkScintilla* int) "gtk_scintilla_set_wrap_mode")
    (macro gtk_scintilla_get_wrap_mode::int (GtkScintilla*) "gtk_scintilla_get_wrap_mode")
    (macro gtk_scintilla_line_down::void (GtkScintilla*) "gtk_scintilla_line_down")
    (macro gtk_scintilla_line_down_extend::void (GtkScintilla*) "gtk_scintilla_line_down_extend")
    (macro gtk_scintilla_line_up::void (GtkScintilla*) "gtk_scintilla_line_up")
    (macro gtk_scintilla_line_up_extend::void (GtkScintilla*) "gtk_scintilla_line_up_extend")
    (macro gtk_scintilla_char_left::void (GtkScintilla*) "gtk_scintilla_char_left")
    (macro gtk_scintilla_char_left_extend::void (GtkScintilla*) "gtk_scintilla_char_left_extend")
    (macro gtk_scintilla_char_right::void (GtkScintilla*) "gtk_scintilla_char_right")
    (macro gtk_scintilla_char_right_extend::void (GtkScintilla*) "gtk_scintilla_char_right_extend")
    (macro gtk_scintilla_word_left::void (GtkScintilla*) "gtk_scintilla_word_left")
    (macro gtk_scintilla_word_left_extend::void (GtkScintilla*) "gtk_scintilla_word_left_extend")
    (macro gtk_scintilla_word_right::void (GtkScintilla*) "gtk_scintilla_word_right")
    (macro gtk_scintilla_word_right_extend::void (GtkScintilla*) "gtk_scintilla_word_right_extend")
    (macro gtk_scintilla_home::void (GtkScintilla*) "gtk_scintilla_home")
    (macro gtk_scintilla_home_extend::void (GtkScintilla*) "gtk_scintilla_home_extend")
    (macro gtk_scintilla_line_end::void (GtkScintilla*) "gtk_scintilla_line_end")
    (macro gtk_scintilla_line_end_extend::void (GtkScintilla*) "gtk_scintilla_line_end_extend")
    (macro gtk_scintilla_document_start::void (GtkScintilla*) "gtk_scintilla_document_start")
    (macro gtk_scintilla_document_start_extend::void (GtkScintilla*) "gtk_scintilla_document_start_extend")
    (macro gtk_scintilla_document_end::void (GtkScintilla*) "gtk_scintilla_document_end")
    (macro gtk_scintilla_document_end_extend::void (GtkScintilla*) "gtk_scintilla_document_end_extend")
    (macro gtk_scintilla_page_up::void (GtkScintilla*) "gtk_scintilla_page_up")
    (macro gtk_scintilla_page_up_extend::void (GtkScintilla*) "gtk_scintilla_page_up_extend")
    (macro gtk_scintilla_page_down::void (GtkScintilla*) "gtk_scintilla_page_down")
    (macro gtk_scintilla_page_down_extend::void (GtkScintilla*) "gtk_scintilla_page_down_extend")
    (macro gtk_scintilla_edit_toggle_overtype::void (GtkScintilla*) "gtk_scintilla_edit_toggle_overtype")
    (macro gtk_scintilla_cancel::void (GtkScintilla*) "gtk_scintilla_cancel")
    (macro gtk_scintilla_delete_back::void (GtkScintilla*) "gtk_scintilla_delete_back")
    (macro gtk_scintilla_tab::void (GtkScintilla*) "gtk_scintilla_tab")
    (macro gtk_scintilla_back_tab::void (GtkScintilla*) "gtk_scintilla_back_tab")
    (macro gtk_scintilla_new_line::void (GtkScintilla*) "gtk_scintilla_new_line")
    (macro gtk_scintilla_form_feed::void (GtkScintilla*) "gtk_scintilla_form_feed")
    (macro gtk_scintilla_v_c_home::void (GtkScintilla*) "gtk_scintilla_v_c_home")
    (macro gtk_scintilla_v_c_home_extend::void (GtkScintilla*) "gtk_scintilla_v_c_home_extend")
    (macro gtk_scintilla_zoom_in::void (GtkScintilla*) "gtk_scintilla_zoom_in")
    (macro gtk_scintilla_zoom_out::void (GtkScintilla*) "gtk_scintilla_zoom_out")
    (macro gtk_scintilla_del_word_left::void (GtkScintilla*) "gtk_scintilla_del_word_left")
    (macro gtk_scintilla_del_word_right::void (GtkScintilla*) "gtk_scintilla_del_word_right")
    (macro gtk_scintilla_line_cut::void (GtkScintilla*) "gtk_scintilla_line_cut")
    (macro gtk_scintilla_line_delete::void (GtkScintilla*) "gtk_scintilla_line_delete")
    (macro gtk_scintilla_line_transpose::void (GtkScintilla*) "gtk_scintilla_line_transpose")
    (macro gtk_scintilla_lower_case::void (GtkScintilla*) "gtk_scintilla_lower_case")
    (macro gtk_scintilla_upper_case::void (GtkScintilla*) "gtk_scintilla_upper_case")
    (macro gtk_scintilla_line_scroll_down::void (GtkScintilla*) "gtk_scintilla_line_scroll_down")
    (macro gtk_scintilla_line_scroll_up::void (GtkScintilla*) "gtk_scintilla_line_scroll_up")
    (macro gtk_scintilla_delete_back_not_line::void (GtkScintilla*) "gtk_scintilla_delete_back_not_line")
    (macro gtk_scintilla_move_caret_inside_view::void (GtkScintilla*) "gtk_scintilla_move_caret_inside_view")
    (macro gtk_scintilla_line_length::int (GtkScintilla* int) "gtk_scintilla_line_length")
    (macro gtk_scintilla_brace_highlight::void (GtkScintilla* long long) "gtk_scintilla_brace_highlight")
    (macro gtk_scintilla_brace_bad_light::void (GtkScintilla* long) "gtk_scintilla_brace_bad_light")
    (macro gtk_scintilla_brace_match::long (GtkScintilla* long) "gtk_scintilla_brace_match")
    (macro gtk_scintilla_get_view_eol::int (GtkScintilla*) "gtk_scintilla_get_view_eol")
    (macro gtk_scintilla_set_view_eol::void (GtkScintilla* int) "gtk_scintilla_set_view_eol")
    (macro gtk_scintilla_get_doc_pointer::int (GtkScintilla*) "gtk_scintilla_get_doc_pointer")
    (macro gtk_scintilla_set_doc_pointer::void (GtkScintilla* int) "gtk_scintilla_set_doc_pointer")
    (macro gtk_scintilla_set_mod_event_mask::void (GtkScintilla* int) "gtk_scintilla_set_mod_event_mask")
    (macro gtk_scintilla_get_edge_column::int (GtkScintilla*) "gtk_scintilla_get_edge_column")
    (macro gtk_scintilla_set_edge_column::void (GtkScintilla* int) "gtk_scintilla_set_edge_column")
    (macro gtk_scintilla_get_edge_mode::int (GtkScintilla*) "gtk_scintilla_get_edge_mode")
    (macro gtk_scintilla_set_edge_mode::void (GtkScintilla* int) "gtk_scintilla_set_edge_mode")
    (macro gtk_scintilla_get_edge_colour::long (GtkScintilla*) "gtk_scintilla_get_edge_colour")
    (macro gtk_scintilla_set_edge_colour::void (GtkScintilla* long) "gtk_scintilla_set_edge_colour")
    (macro gtk_scintilla_search_anchor::void (GtkScintilla*) "gtk_scintilla_search_anchor")
    (macro gtk_scintilla_search_next::int (GtkScintilla* int string) "gtk_scintilla_search_next")
    (macro gtk_scintilla_search_prev::int (GtkScintilla* int string) "gtk_scintilla_search_prev")
    (macro gtk_scintilla_set_caret_policy::void (GtkScintilla* int int) "gtk_scintilla_set_caret_policy")
    (macro gtk_scintilla_lines_on_screen::int (GtkScintilla*) "gtk_scintilla_lines_on_screen")
    (macro gtk_scintilla_use_pop_up::void (GtkScintilla* int) "gtk_scintilla_use_pop_up")
    (macro gtk_scintilla_selection_is_rectangle::int (GtkScintilla*) "gtk_scintilla_selection_is_rectangle")
    (macro gtk_scintilla_set_zoom::void (GtkScintilla* int) "gtk_scintilla_set_zoom")
    (macro gtk_scintilla_get_zoom::int (GtkScintilla*) "gtk_scintilla_get_zoom")
    (macro gtk_scintilla_create_document::int (GtkScintilla*) "gtk_scintilla_create_document")
    (macro gtk_scintilla_add_ref_document::void (GtkScintilla* int) "gtk_scintilla_add_ref_document")
    (macro gtk_scintilla_release_document::void (GtkScintilla* int) "gtk_scintilla_release_document")
    (macro gtk_scintilla_get_mod_event_mask::int (GtkScintilla*) "gtk_scintilla_get_mod_event_mask")
    (macro gtk_scintilla_set_focus::void (GtkScintilla* int) "gtk_scintilla_set_focus")
    (macro gtk_scintilla_get_focus::int (GtkScintilla*) "gtk_scintilla_get_focus")
    (macro gtk_scintilla_set_status::void (GtkScintilla* int) "gtk_scintilla_set_status")
    (macro gtk_scintilla_get_status::int (GtkScintilla*) "gtk_scintilla_get_status")
    (macro gtk_scintilla_set_mouse_down_captures::void (GtkScintilla* int) "gtk_scintilla_set_mouse_down_captures")
    (macro gtk_scintilla_get_mouse_down_captures::int (GtkScintilla*) "gtk_scintilla_get_mouse_down_captures")
    (macro gtk_scintilla_set_cursor::void (GtkScintilla* int) "gtk_scintilla_set_cursor")
    (macro gtk_scintilla_get_cursor::int (GtkScintilla*) "gtk_scintilla_get_cursor")
    (macro gtk_scintilla_set_control_char_symbol::void (GtkScintilla* int) "gtk_scintilla_set_control_char_symbol")
    (macro gtk_scintilla_get_control_char_symbol::int (GtkScintilla*) "gtk_scintilla_get_control_char_symbol")
    (macro gtk_scintilla_word_part_left::void (GtkScintilla*) "gtk_scintilla_word_part_left")
    (macro gtk_scintilla_word_part_left_extend::void (GtkScintilla*) "gtk_scintilla_word_part_left_extend")
    (macro gtk_scintilla_word_part_right::void (GtkScintilla*) "gtk_scintilla_word_part_right")
    (macro gtk_scintilla_word_part_right_extend::void (GtkScintilla*) "gtk_scintilla_word_part_right_extend")
    (macro gtk_scintilla_set_visible_policy::void (GtkScintilla* int int) "gtk_scintilla_set_visible_policy")
    (macro gtk_scintilla_del_line_left::void (GtkScintilla*) "gtk_scintilla_del_line_left")
    (macro gtk_scintilla_del_line_right::void (GtkScintilla*) "gtk_scintilla_del_line_right")
    (macro gtk_scintilla_set_x_offset::void (GtkScintilla* int) "gtk_scintilla_set_x_offset")
    (macro gtk_scintilla_get_x_offset::int (GtkScintilla*) "gtk_scintilla_get_x_offset")
    (macro gtk_scintilla_grab_focus::void (GtkScintilla*) "gtk_scintilla_grab_focus")
    (macro gtk_scintilla_start_record::void (GtkScintilla*) "gtk_scintilla_start_record")
    (macro gtk_scintilla_stop_record::void (GtkScintilla*) "gtk_scintilla_stop_record")
    (macro gtk_scintilla_set_lexer::void (GtkScintilla* int) "gtk_scintilla_set_lexer")
    (macro gtk_scintilla_get_lexer::int (GtkScintilla*) "gtk_scintilla_get_lexer")
    (macro gtk_scintilla_colourise::void (GtkScintilla* long long) "gtk_scintilla_colourise")
    (macro gtk_scintilla_set_property::void (GtkScintilla* string string) "gtk_scintilla_set_property")
    (macro gtk_scintilla_set_keywords::void (GtkScintilla* int string) "gtk_scintilla_set_keywords")
    (macro gtk_scintilla_set_lexer_language::void (GtkScintilla* string) "gtk_scintilla_set_lexer_language")
    (type s-_GtkScintilla (struct (parent::GtkFrame "parent") (scintilla::GtkWidget* "scintilla") (accel_group::GtkAccelGroup* "accel_group")) "struct _GtkScintilla")
    (type GtkScintilla s-_GtkScintilla "GtkScintilla")
   (type s-_GtkScintillaClass (struct (parent_class::GtkFrameClass "parent_class") (style_needed::*GtkWidget*,int->void "style_needed") (char_added::*GtkWidget*,int->void "char_added") (save_point_reached::*GtkWidget*->void "save_point_reached") (save_point_left::*GtkWidget*->void "save_point_left") (modify_attempt_ro::*GtkWidget*->void "modify_attempt_ro") (key::*GtkWidget*,int,int->void "key") (double_click::*GtkWidget*->void "double_click") (update_ui::*GtkWidget*->void "update_ui") (modified::*GtkWidget*->void "modified") (macro_record::*GtkWidget*,int,int,int->void "macro_record") (margin_click::*GtkWidget*,int,int,int->void "margin_click") (need_shown::*GtkWidget*,int,int->void "need_shown") (painted::*GtkWidget*->void "painted") (user_list_selection::*GtkWidget*,int,string->void "user_list_selection") (uri_dropped::*GtkWidget*,string->void "uri_dropped")) "struct _GtkScintillaClass")
   (type GtkScintillaClass s-_GtkScintillaClass "GtkScintillaClass")
;   (type GtkWidget* (pointer GtkWidget) "GtkWidget *")
;   (type GtkAccelGroup* (pointer GtkAccelGroup) "GtkAccelGroup *")
    (type GtkWidget*,int->void "void ($(GtkWidget *,int))")
    (type *GtkWidget*,int->void (function void (GtkWidget* int)) "void ((*$)(GtkWidget *,int))")
;   (type GtkWidget*->void "void ($(GtkWidget *))")
 ;  (type *GtkWidget*->void (function void (GtkWidget*)) "void ((*$)(GtkWidget *))")

        (type GtkWidget*,int,int->void "void ($(GtkWidget *,int,int))")
    (type *GtkWidget*,int,int->void (function void (GtkWidget* int int)) "void ((*$)(GtkWidget *,int,int))")
    (type GtkWidget*,int,int,int->void "void ($(GtkWidget *,int,int,int))")
    (type *GtkWidget*,int,int,int->void (function void (GtkWidget* int int int)) "void ((*$)(GtkWidget *,int,int,int))")
    (type GtkWidget*,int,string->void "void ($(GtkWidget *,int,char *))")
    (type *GtkWidget*,int,string->void (function void (GtkWidget* int string)) "void ((*$)(GtkWidget *,int,char *))")
    (type GtkWidget*,string->void "void ($(GtkWidget *,char *))")
    (type *GtkWidget*,string->void (function void (GtkWidget* string)) "void ((*$)(GtkWidget *,char *))")

;      (type void->guint "guint ($(void))")
;   (type void->GtkWidget* "GtkWidget *($(void))")
     (type long* (pointer long) "long *")
    (type GtkScintilla*,int,string,long,long,long*,long*->long "long ($(GtkScintilla *,int,char *,long,long,long *,long *))")
    (type GtkScintilla*,int,string->void "void ($(GtkScintilla *,int,char *))")
    (type GtkScintilla*,long,string->void "void ($(GtkScintilla *,long,char *))")
    (type GtkScintilla*->void "void ($(GtkScintilla *))")
    (type GtkScintilla*->int "int ($(GtkScintilla *))")
    (type GtkScintilla*,long->int "int ($(GtkScintilla *,long))")
    (type GtkScintilla*->long "long ($(GtkScintilla *))")
    (type GtkScintilla*,int->void "void ($(GtkScintilla *,int))")
    (type GtkScintilla*,int->int "int ($(GtkScintilla *,int))")
    (type GtkScintilla*,int,int->int "int ($(GtkScintilla *,int,int))")
    (type GtkScintilla*,long->void "void ($(GtkScintilla *,long))")
    (type GtkScintilla*,int,string->int "int ($(GtkScintilla *,int,char *))")
    (type GtkScintilla*,long,int->void "void ($(GtkScintilla *,long,int))")
    (type GtkScintilla*,int,int->void "void ($(GtkScintilla *,int,int))")
    (type GtkScintilla*,int,long->void "void ($(GtkScintilla *,int,long))")
    (type GtkScintilla*,string->void "void ($(GtkScintilla *,char *))")
    (type GtkScintilla*,int->long "long ($(GtkScintilla *,int))")
    (type GtkScintilla*,long,long->void "void ($(GtkScintilla *,long,long))")
    (type GtkScintilla*,string->int "int ($(GtkScintilla *,char *))")
    (type GtkScintilla*,long->long "long ($(GtkScintilla *,long))")
    (type GtkScintilla*,string,string->void "void ($(GtkScintilla *,char *,char *))")
    ;; end of /usr/include/gtkscintilla.h
    ))
